### ISSUE TITLE
The JAXBs seem to be wrong

### ISSUE THREAD

**Issue by Vampire** [mirthas/FritzTR064#3]
If I try to use your library, I only get `NullPointerExceptions`. If I use the constructor without credentials in `readIGDDESC()`, if I use the constructor with credentials in `readTR64()`. In both cases the `NPE` happens when calling `device.getFriendlyName()`, as the `RootType` or `RootType2` objects are not populated.

If I use the following code

```
JAXBContext jaxbContext = JAXBContext.newInstance(RootType.class);
Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();
// the following line is important to get the validation error as Exception,
// otherwise the error is simply swallowed
unmarshaller.setEventHandler(event -> false);
unmarshaller.unmarshal(new URL("http://fritz.box:49000/tr64desc.xml"));
```

I get the exception

```
Exception in thread "main" javax.xml.bind.UnmarshalException: unerwartetes Element (URI:"urn:dslforum-org:device-1-0", lokal:"major"). Erwartete Elemente sind <{}minor>,<{}major>
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:726)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.childElement(Loader.java:90)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.childElement(StructureLoader.java:237)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:556)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:276)
    at my class
```

This happens because your JaxBs only have the namespace for the root element, but the actual XML files delivered by FRITZ!Box have the default namespace set and thus all elements have that namespace.

**Comment by Aypac** [comment]
Having the same issue. I would love to see this library working again. Vampire, were you able to fix this?

**Comment by Inguiotar** [comment]
Maybe a little late, but for future reference: The JAXB annotations have been fixed in my fork.

**Comment by Vampire** [comment]
@Aypac I started to fix these locally, then I was distracted by other projects. When coming back to this, I realized that TR-064 actually is an extension of UPnP. So I switched to using a proper UPNP library and with that it works fine. The SOAP calls are simply a part of the UPnP protocol and it is not necessary to do these manually.
